// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type GithubUser struct {
	ID        int64
	Timestamp sql.NullTime
	Name      string
	Alph      int64
	Present   bool
}
